### ISSUE TITLE
Events Server.

### ISSUE THREAD

**Issue by whitebook** [uhppoted/httpd#3]
I was curious if perhaps we can make the events server over websocket? I see the events periodically in the console so I would imagine its possible to have some sort of websocket server push that to the UI.

Is this something that might be on your roadmap?

**Comment by uhppoted** [comment]
Hi,

I'll add a roadmap to the README so that at least there is some indication of where this sub-project thinks it may be going, but yes, the intention is to move to _websockets_ in the near'ish future. Relying on polling to get events and controller statuses to a UI client is iffy at best.

However, if you were asking about a standalone events server, then there are a couple of ways to implement one with the existing code:

- for more-or-less real-time event alerting, the [CLI](https://github.com/uhppoted/uhppote-cli) `listen` command can be wrapped in a _service_ that pipes received events to another process for storage and/or broadcast
- for event collation and reporting, the [CLI](https://github.com/uhppoted/uhppote-cli) `get-events` command can be run inside a _cron_ job that periodically retrieves and exports the events to e.g. a _sqlite_ database
- _[uhppoted-mqtt](https://github.com/uhppoted/uhppoted-mqtt)_ pushes received events to an MQTT server. Most MQTT server implementations support websocket client connections so a websocket client can subscribe to the configured events topic to receive more-or-less real-time events
- the _[node-red-contrib-uhppoted](https://github.com/uhppoted/node-red-contrib-uhppoted)_ module includes a node that listens for events. NodeRED includes support for websockets in the base library so it's relatively straightforward to set up a flow that forwards received events to a websocket client.

Hope that answers your question? Or if you could perhaps elaborate a bit more on the use case..

**Comment by whitebook** [comment]
I was referring to real-time events in the WEB GUI... I see a link on the NAV for events. (which I dont think has been implemented yet from what I can tell)...

**Comment by uhppoted** [comment]
Ah, ok - thanks for clarifying. Yes, an events view is on the _TODO_ list but as yet only the `NAV` bar item is there.

Have added an initial (and very drafty) roadmap to the [README](https://github.com/uhppoted/httpd/blob/master/README.md) that should hopefully outline where the project is going.

Please feel free to comment :-) !
